name: Update Greeting

on:
  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: write

jobs:
  atualizar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Executar greeting.js
        run: node greeting.js

      - name: Configurar usuário Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit e Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "update greeting on README"
          branch: main
